# Generated by Django 5.2.8 on 2025-12-01 04:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0003_add_two_factor_auth'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlacklistEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blacklisted_emails', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Blacklist Email',
                'verbose_name_plural': 'Blacklist Emails',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlacklistIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blacklisted_ips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Blacklist IP Address',
                'verbose_name_plural': 'Blacklist IP Addresses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlacklistLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(unique=True)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blacklisted_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Blacklist Link',
                'verbose_name_plural': 'Blacklist Links',
                'ordering': ['-created_at'],
            },
        ),
    ]
