# Generated by Django 5.2.8 on 2025-12-01 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0004_blacklistemail_blacklistip_blacklistlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='gateway_payment_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('paypal', 'PayPal'), ('stripe', 'Stripe'), ('aba', 'ABA PayWay'), ('wing', 'Wing Bank'), ('pipay', 'Pi Pay'), ('khqr', 'KHQR'), ('usdt', 'USDT'), ('card', 'Credit Card'), ('truemoney', 'TrueMoney')], max_length=20),
        ),
    ]
