# Generated by Django 5.2.8 on 2025-12-02 01:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0005_add_gateway_payment_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text="Unique setting key (e.g., 'site_name', 'min_deposit')", max_length=100, unique=True)),
                ('value', models.TextField(blank=True, help_text='Setting value')),
                ('default_value', models.TextField(blank=True, help_text='Default value if not set')),
                ('setting_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('boolean', 'Boolean'), ('email', 'Email'), ('url', 'URL'), ('textarea', 'Textarea'), ('json', 'JSON')], default='text', max_length=20)),
                ('group', models.CharField(choices=[('general', 'General'), ('payment', 'Payment'), ('email', 'Email'), ('api', 'API'), ('security', 'Security'), ('seo', 'SEO'), ('social', 'Social Media'), ('maintenance', 'Maintenance')], default='general', max_length=20)),
                ('label', models.CharField(help_text='Human-readable label', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Help text for this setting')),
                ('is_public', models.BooleanField(default=False, help_text='Can be accessed via API/public')),
                ('is_encrypted', models.BooleanField(default=False, help_text='Should this value be encrypted?')),
                ('order', models.IntegerField(default=0, help_text='Display order within group')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'System Setting',
                'verbose_name_plural': 'System Settings',
                'ordering': ['group', 'order', 'key'],
            },
        ),
    ]
