# Generated by Django 5.2.8 on 2025-12-03 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0009_add_paymen_expire'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='platform',
            field=models.CharField(choices=[('ig', 'Instagram'), ('fb', 'Facebook'), ('tt', 'TikTok'), ('yt', 'YouTube'), ('tw', 'Twitter/X'), ('sp', 'Spotify'), ('li', 'LinkedIn'), ('dc', 'Discord'), ('sc', 'Snapchat'), ('twitch', 'Twitch'), ('tg', 'Telegram'), ('google', 'Google'), ('sh', 'Shopee'), ('web', 'Website Traffic'), ('review', 'Reviews'), ('other', 'Others')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_type',
            field=models.CharField(choices=[('ig', 'Instagram'), ('fb', 'Facebook'), ('tt', 'TikTok'), ('yt', 'YouTube'), ('tw', 'Twitter/X'), ('sp', 'Spotify'), ('li', 'LinkedIn'), ('dc', 'Discord'), ('sc', 'Snapchat'), ('twitch', 'Twitch'), ('tg', 'Telegram'), ('google', 'Google'), ('sh', 'Shopee'), ('web', 'Website Traffic'), ('review', 'Reviews'), ('other', 'Others')], max_length=10),
        ),
    ]
