# Generated by Django 5.2.8 on 2025-12-03 14:53

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0010_add_platform_to_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingPromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promotion_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('title', models.CharField(help_text='Promotion title', max_length=200)),
                ('title_km', models.CharField(blank=True, help_text='Khmer translation', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Promotion description')),
                ('description_km', models.TextField(blank=True, help_text='Khmer description')),
                ('promotion_type', models.CharField(choices=[('banner', 'Banner'), ('popup', 'Popup'), ('notification', 'Notification'), ('email', 'Email Campaign'), ('discount', 'Discount Campaign'), ('flash_sale', 'Flash Sale'), ('free_bonus', 'Free Bonus')], default='banner', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='promotions/banners/')),
                ('banner_image_mobile', models.ImageField(blank=True, null=True, upload_to='promotions/banners/mobile/')),
                ('background_color', models.CharField(default='#007bff', help_text='Hex color code', max_length=7)),
                ('text_color', models.CharField(default='#ffffff', help_text='Hex color code', max_length=7)),
                ('target_audience', models.CharField(choices=[('all', 'All Users'), ('new_users', 'New Users'), ('active_users', 'Active Users'), ('inactive_users', 'Inactive Users'), ('high_spenders', 'High Spenders'), ('resellers', 'Resellers'), ('specific_users', 'Specific Users')], default='all', max_length=20)),
                ('display_location', models.CharField(choices=[('homepage', 'Homepage'), ('dashboard', 'User Dashboard'), ('services', 'Services Page'), ('checkout', 'Checkout Page'), ('all_pages', 'All Pages')], default='homepage', max_length=20)),
                ('start_date', models.DateTimeField(help_text='When promotion starts')),
                ('end_date', models.DateTimeField(help_text='When promotion ends')),
                ('display_priority', models.IntegerField(default=0, help_text='Higher number = higher priority')),
                ('cta_text', models.CharField(blank=True, help_text="Button text (e.g., 'Shop Now')", max_length=100)),
                ('cta_link', models.CharField(blank=True, help_text='Button link', max_length=500)),
                ('discount_code', models.CharField(blank=True, help_text='Associated coupon code', max_length=50)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('bonus_amount', models.DecimalField(decimal_places=2, default=0, help_text='Free balance bonus', max_digits=10)),
                ('views_count', models.IntegerField(default=0, help_text='How many times viewed')),
                ('clicks_count', models.IntegerField(default=0, help_text='How many times clicked')),
                ('conversions_count', models.IntegerField(default=0, help_text='How many conversions')),
                ('is_active', models.BooleanField(default=True)),
                ('auto_expire', models.BooleanField(default=True, help_text='Auto expire after end_date')),
                ('show_countdown', models.BooleanField(default=False, help_text='Show countdown timer')),
                ('max_views_per_user', models.IntegerField(default=0, help_text='0 = unlimited')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_promotions', to=settings.AUTH_USER_MODEL)),
                ('specific_users', models.ManyToManyField(blank=True, related_name='targeted_promotions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Marketing Promotion',
                'verbose_name_plural': 'Marketing Promotions',
                'ordering': ['-display_priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromotionClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('clicked_at', models.DateTimeField(auto_now_add=True)),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_clicks', to='panel.marketingpromotion')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotion_clicks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Promotion Click',
                'verbose_name_plural': 'Promotion Clicks',
                'ordering': ['-clicked_at'],
            },
        ),
        migrations.CreateModel(
            name='PromotionConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversion_type', models.CharField(choices=[('order', 'Order Placed'), ('deposit', 'Deposit Made'), ('signup', 'User Signup'), ('coupon_used', 'Coupon Used')], max_length=20)),
                ('conversion_value', models.DecimalField(decimal_places=2, default=0, help_text='Value of conversion (e.g., order amount)', max_digits=10)),
                ('converted_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='panel.order')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='panel.payment')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversions', to='panel.marketingpromotion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_conversions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Promotion Conversion',
                'verbose_name_plural': 'Promotion Conversions',
                'ordering': ['-converted_at'],
            },
        ),
        migrations.CreateModel(
            name='PromotionView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_views', to='panel.marketingpromotion')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotion_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Promotion View',
                'verbose_name_plural': 'Promotion Views',
                'ordering': ['-viewed_at'],
            },
        ),
    ]
