# Generated by Django 5.2.8 on 2025-12-04 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0011_add_marketing_promotions'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_code', models.CharField(choices=[('ig', 'Instagram'), ('fb', 'Facebook'), ('tt', 'TikTok'), ('yt', 'YouTube'), ('tw', 'Twitter/X'), ('sp', 'Spotify'), ('li', 'LinkedIn'), ('dc', 'Discord'), ('sc', 'Snapchat'), ('twitch', 'Twitch'), ('tg', 'Telegram'), ('google', 'Google'), ('sh', 'Shopee'), ('web', 'Website Traffic'), ('review', 'Reviews'), ('other', 'Others')], max_length=20, unique=True)),
                ('name', models.CharField(help_text='Display name', max_length=100)),
                ('name_km', models.CharField(blank=True, help_text='Khmer translation', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Platform description')),
                ('description_km', models.TextField(blank=True, help_text='Khmer description')),
                ('icon', models.CharField(blank=True, help_text='Icon class or path', max_length=100)),
                ('icon_image', models.ImageField(blank=True, null=True, upload_to='social_networks/icons/')),
                ('color', models.CharField(default='#000000', help_text='Brand color (hex)', max_length=7)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='social_networks/logos/')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Under Maintenance'), ('deprecated', 'Deprecated')], default='active', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Available for orders')),
                ('is_featured', models.BooleanField(default=False, help_text='Show in featured section')),
                ('display_order', models.IntegerField(default=0, help_text='Display order in lists')),
                ('website_url', models.URLField(blank=True, help_text='Official website')),
                ('documentation_url', models.URLField(blank=True, help_text='API documentation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Social Network',
                'verbose_name_plural': 'Social Networks',
                'ordering': ['display_order', 'name'],
            },
        ),
    ]
