# Generated by Django 5.2.8 on 2025-12-04 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0012_socialnetwork'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['category', 'social_network__display_order', 'name']},
        ),
        migrations.AlterModelOptions(
            name='servicecategory',
            options={'ordering': ['order', 'name'], 'verbose_name_plural': 'Service Categories'},
        ),
        migrations.AddField(
            model_name='service',
            name='social_network',
            field=models.ForeignKey(blank=True, help_text='Social network platform for this service', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='panel.socialnetwork'),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='social_network',
            field=models.ForeignKey(blank=True, help_text='Optional: Link category to a specific social network platform', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_categories', to='panel.socialnetwork'),
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='panel.servicecategory'),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_type',
            field=models.CharField(choices=[('ig', 'Instagram'), ('fb', 'Facebook'), ('tt', 'TikTok'), ('yt', 'YouTube'), ('tw', 'Twitter/X'), ('sp', 'Spotify'), ('li', 'LinkedIn'), ('dc', 'Discord'), ('sc', 'Snapchat'), ('twitch', 'Twitch'), ('tg', 'Telegram'), ('google', 'Google'), ('sh', 'Shopee'), ('web', 'Website Traffic'), ('review', 'Reviews'), ('other', 'Others')], help_text='Platform code (legacy field, use social_network if available)', max_length=10),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['social_network', 'is_active'], name='panel_servi_social__1ba545_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['category', 'is_active'], name='panel_servi_categor_48fbd4_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['service_type', 'is_active'], name='panel_servi_service_fb79c9_idx'),
        ),
    ]
