# Generated by Django 5.2.8 on 2025-12-04 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0013_alter_service_options_alter_servicecategory_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['category', 'name']},
        ),
        migrations.RemoveIndex(
            model_name='service',
            name='panel_servi_social__1ba545_idx',
        ),
        migrations.RemoveIndex(
            model_name='service',
            name='panel_servi_categor_48fbd4_idx',
        ),
        migrations.RemoveIndex(
            model_name='service',
            name='panel_servi_service_fb79c9_idx',
        ),
        migrations.RemoveField(
            model_name='service',
            name='social_network',
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='panel.servicecategory'),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_type',
            field=models.CharField(choices=[('ig', 'Instagram'), ('fb', 'Facebook'), ('tt', 'TikTok'), ('yt', 'YouTube'), ('tw', 'Twitter/X'), ('sp', 'Spotify'), ('li', 'LinkedIn'), ('dc', 'Discord'), ('sc', 'Snapchat'), ('twitch', 'Twitch'), ('tg', 'Telegram'), ('google', 'Google'), ('sh', 'Shopee'), ('web', 'Website Traffic'), ('review', 'Reviews'), ('other', 'Others')], max_length=10),
        ),
    ]
