# Generated by Django 5.2.8 on 2025-12-04 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0014_alter_service_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecategory',
            name='social_network',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='panel.socialnetwork'),
        ),
    ]
